import './global.css';
import Header from './components/header';
import Footer from './components/footer';

export const metadata = {
  title: 'Welcome to api-software', description: 'Generated by create-nx-workspace'
};

export default function RootLayout({
                                     children
                                   }: {
  children: React.ReactNode;
}) {
  return (<html lang="vi">
  <body>
  <Header />
  {children}
  <Footer />
  </body>
  </html>);
}
